create table lesson (
       id bigint generated by default as identity,
        createdate timestamp,
        description varchar(255),
        name varchar(255),
        status bigint,
        primary key (id)
    );
 
    
    create table persistent_logins (
       series varchar(64) not null,
        last_used timestamp not null,
        token varchar(64) not null,
        username varchar(64) not null,
        primary key (series)
    );

    
    create table role (
       id bigint generated by default as identity,
        createdate timestamp,
        name varchar(255),
        primary key (id)
    );

    
    create table user (
       id bigint generated by default as identity,
        createdate timestamp,
        email varchar(255),
        grade varchar(255),
        name varchar(255),
        password varchar(255),
        sex integer,
        primary key (id)
    );

    
    create table user_lesson (
       user_id bigint not null,
        lesson_id bigint not null
    );

    
    create table user_role (
       user_id bigint not null,
        roles_id bigint not null
    );

    
    alter table user_lesson 
       add constraint FKaoad4p1ijn3vbv7yyn1k52uk8 
       foreign key (lesson_id) 
       references lesson;
 
    
    alter table user_lesson 
       add constraint FK90gnos9175k1nc8esxvl1u44n 
       foreign key (user_id) 
       references user;
 
    
    alter table user_role 
       add constraint FKeog8p06nu33ihk13roqnrp1y6 
       foreign key (roles_id) 
       references role;

    
    alter table user_role 
       add constraint FK859n2jvi8ivhui0rl0esws6o 
       foreign key (user_id) 
       references user;